export const SET_ITEM_STATE = "SET_ITEM_STATE"
export const SET_BASKET_ITEMS = "SET_BASKET_ITEMS"
export const SET_PAGE = "SET_PAGE"
export const SET_TOTAL_COUNT = "SET_TOTAL_COUNT"
export const SET_LIMIT = "SET_LIMIT"